apiVersion: v1
kind: Service
metadata:
  name: tcp-k8s-service
  labels:
    app: tcp-k8s-service
spec:
  type: NodePort
  ports:
    - port: 
      targetPort: 
      protocol: TCP
  selector:
      app: 
