apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app: tcp-k8s-app
spec:
  replicas: 
  selector:
    matchLabels:
       app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: tcp-server
        image: 
        ports:
          - containerPort: 
            name: tcp-port

